In [1]:
import numpy as np

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
index = [2,3,5,9]
x[index]

array([2, 3, 5, 9])

In [14]:
index = np.array([[1,2],[3,4]])
x[index]

array([[1, 2],
       [3, 4]])

In [15]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
row = [0,1,2]
col = [1,2,3]
x[row,col]

array([ 1,  6, 11])

In [22]:
x[2,col]

array([ 9, 10, 11])

In [23]:
x[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [43]:
x[row,1]

array([1, 5, 9])

In [44]:
x[row,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [25]:
col = [True,False,True,True]
x[col]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
x[:,col]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15]])

In [29]:
x<9

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [32]:
x[x<9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
x[x<9].reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
np.sum(x<=3)

4

In [35]:
np.count_nonzero(x<=3)

4

In [36]:
np.any(x==0)

True

In [37]:
np.any(x<0)

False

In [38]:
np.all(x>=0)

True

In [39]:
np.all(x>0)

False

In [40]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.sum(x%2==0,axis=1)

array([2, 2, 2, 2])

In [46]:
np.sum(x%2==0,axis=0)

array([4, 0, 4, 0])

In [48]:
np.all(x>0,axis=1)

array([False,  True,  True,  True])

In [52]:
np.any(x==3,axis=1)

array([ True, False, False, False])

In [53]:
np.any(x==3,axis=0)

array([False, False, False,  True])

In [54]:
np.sum((x>3)&(x<9))

5

In [55]:
np.sum((x>3)|(x<9))

16

In [56]:
np.sum((x!=1))

15

In [57]:
np.sum(~(x==1))

15

In [64]:
x[:,3]%3==0

array([ True, False, False,  True])

In [63]:
x[x[:,3]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])