In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
x.ndim

1

In [7]:
y.ndim

2

In [8]:
x.shape

(10,)

In [9]:
y.shape

(3, 5)

In [10]:
x.size

10

In [11]:
y.size

15

In [12]:
x[-1]

9

In [13]:
y[2,2]

12

In [14]:
x[0:5]

array([0, 1, 2, 3, 4])

In [15]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x[::3]

array([0, 3, 6, 9])

In [17]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
y[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [19]:
y[0:3,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [20]:
y[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [21]:
y[0]

array([0, 1, 2, 3, 4])

In [22]:
y[0,:]

array([0, 1, 2, 3, 4])

In [23]:
y[0,:].ndim

1

In [24]:
y[:,0]

array([ 0,  5, 10])

In [25]:
y[:,0].ndim

1

In [26]:
suby = y[0:2,0:3]
suby

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
suby[0,0] = 100
suby

array([[100,   1,   2],
       [  5,   6,   7]])

In [28]:
y

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [29]:
y[0,0] = 0
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
#创建副本.copy()，修改元素不改变原数组的值
suby = y[0:2,0:3].copy()
suby[0,0] = 100
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
x.shape

(10,)

In [32]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a  = x.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
b = x.reshape(1,10)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
b.ndim

2

In [38]:
b.shape

(1, 10)

In [39]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [40]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a = x.reshape(10,-1)
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])