In [2]:
import numpy as np

In [13]:
np.__version__

'1.14.2'

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5]

5

In [16]:
nparr.dtype

dtype('int32')

In [17]:
nparr2 = np.array([1,2,3.0])
nparr2

array([1., 2., 3.])

In [18]:
np.zeros(shape=(3,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(shape=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [35]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [40]:
np.random.randint(0,10)

8

In [41]:
np.random.randint(0,10,size=10)

array([1, 8, 6, 1, 6, 4, 9, 7, 0, 0])

In [42]:
np.random.randint(0,1,size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
np.random.randint(0,2,size=(3,5))

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0]])

In [49]:
#每次产生的随机数一样
np.random.seed(10)
np.random.randint(0,2,size=(3,5))

array([[1, 1, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [0, 1, 1, 0, 0]])

In [52]:
np.random.random(5)

array([0.06556327, 0.05644419, 0.76545582, 0.01178803, 0.61194334])

In [61]:
np.random.random(size=(3,5))

array([[0.38286511, 0.2248728 , 0.1146488 , 0.58301705, 0.23264106],
       [0.55651819, 0.52381088, 0.35095822, 0.70533161, 0.82070374],
       [0.134563  , 0.60472616, 0.28314828, 0.50640782, 0.03846043]])

In [56]:
np.random.normal()

-0.024193190232279643

In [62]:
np.random.normal(0,1,size=(2,3))

array([[-0.61081384, -1.12679091,  1.513816  ],
       [-0.60729449,  0.4183223 ,  0.98655675]])

In [63]:
np.random.normal?

In [65]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [3]:
np.random.random?