In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
np.concatenate([A,A],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
a = np.array([666,666,666])
np.concatenate([A,a.reshape(1,-1)],axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [9]:
a = np.array([666,666,666])
np.vstack([A,a])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [10]:
B = np.array([1,2,3,4]).reshape(2,2)
B

array([[1, 2],
       [3, 4]])

In [11]:
np.hstack([B,B])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x1,x2,x3 = np.split(x,[3,6])

In [14]:
x1

array([0, 1, 2])

In [15]:
x2

array([3, 4, 5])

In [16]:
x3

array([6, 7, 8, 9])

In [17]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
a1,a2 = np.split(a,[2],axis=0)

In [19]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
a1,a2 = np.split(a,[2],axis=1)

In [22]:
a1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [23]:
a2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [24]:
upper,lower = np.vsplit(a,[3])

In [25]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
lower

array([[12, 13, 14, 15]])

In [27]:
left,right = np.hsplit(a,[3])

In [28]:
left

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [29]:
right

array([[ 3],
       [ 7],
       [11],
       [15]])

In [30]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
x,y = np.hsplit(data,[-1])

In [32]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [33]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [34]:
y[:,0]

array([ 3,  7, 11, 15])

In [38]:
data[0,:]

array([0, 1, 2, 3])