In [1]:
import numpy as np

In [2]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
np.min(x)

0

In [4]:
np.argmin(x)

0

In [5]:
np.max(x)

15

In [6]:
np.argmax(x)

15

In [7]:
#使向量乱序排列
np.random.shuffle(x)
x

array([ 2,  5, 11,  7,  0, 12,  8,  6,  3, 13,  9, 15, 14, 10,  4,  1])

In [8]:
x = np.sort(x)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
x = np.sort?

In [10]:
x = np.random.randint(3,size=(4,4))
x

array([[0, 1, 2, 1],
       [1, 1, 2, 2],
       [0, 0, 0, 2],
       [1, 1, 1, 2]])

In [11]:
np.sort(x)

array([[0, 1, 1, 2],
       [1, 1, 2, 2],
       [0, 0, 0, 2],
       [1, 1, 1, 2]])

In [12]:
np.sort(x,axis=1)

array([[0, 1, 1, 2],
       [1, 1, 2, 2],
       [0, 0, 0, 2],
       [1, 1, 1, 2]])

In [13]:
np.sort(x,axis=0)

array([[0, 0, 0, 1],
       [0, 1, 1, 2],
       [1, 1, 2, 2],
       [1, 1, 2, 2]])

In [22]:
x = np.arange(5)
np.random.shuffle(x)
x

array([4, 2, 0, 3, 1])

In [23]:
#从最小的元素开始，索引在原数组中的位置
np.argsort(x)

array([2, 4, 1, 3, 0], dtype=int64)

In [24]:
x[np.argsort(x)]

array([0, 1, 2, 3, 4])

In [39]:
x = np.arange(16)
np.random.shuffle(x)
x

array([ 2,  8, 14, 11,  5,  0,  7,  4, 10,  1, 12,  6, 15, 13,  3,  9])

In [41]:
#kth之前的都比kth小，之后的比kth大
np.partition(x,kth=6)

array([ 0,  2,  3,  1,  4,  5,  6,  8,  7,  9, 11, 10, 15, 13, 14, 12])

In [38]:
np.partition?

In [45]:
x = np.arange(10)
np.random.shuffle(x)
x

array([2, 3, 7, 0, 8, 1, 5, 9, 6, 4])

In [46]:
np.partition(x,5)

array([3, 2, 1, 0, 4, 5, 6, 7, 8, 9])

In [47]:
#得到的是np.partition对应的索引值的矩阵
np.argpartition(x,5)

array([1, 0, 5, 3, 9, 6, 8, 2, 4, 7], dtype=int64)