# 聚合操作

In [1]:
import numpy as np

In [4]:
L = np.random.random(size=100)
L

array([0.25890482, 0.70354264, 0.61453266, 0.42099585, 0.97607688,
       0.05076812, 0.67269688, 0.76317937, 0.89008489, 0.62437758,
       0.90073146, 0.33600584, 0.05818999, 0.5968244 , 0.90941731,
       0.49912426, 0.35170935, 0.59504982, 0.23981552, 0.34030369,
       0.21197709, 0.62240348, 0.54480118, 0.71126709, 0.13972218,
       0.12838315, 0.7404062 , 0.93754945, 0.83533512, 0.65142033,
       0.25739852, 0.26196976, 0.37603418, 0.33319455, 0.47252677,
       0.6705899 , 0.49254863, 0.6074094 , 0.41667549, 0.52354733,
       0.00630398, 0.7753194 , 0.95509817, 0.77676609, 0.97661027,
       0.93999381, 0.59893093, 0.82406398, 0.74751745, 0.98455482,
       0.91610653, 0.61896805, 0.17792165, 0.74389821, 0.08058461,
       0.35171823, 0.26570457, 0.23785799, 0.2891001 , 0.01465284,
       0.58230309, 0.34092235, 0.21278324, 0.3356938 , 0.69305303,
       0.46834177, 0.4036188 , 0.71387116, 0.66958322, 0.06046242,
       0.16243671, 0.29796649, 0.21973685, 0.94398699, 0.65451

In [5]:
sum(L)

52.12980732559383

In [6]:
np.sum(L)

52.129807325593816

In [13]:
data = np.random.random(size=1000000)
%timeit sum(data)
%timeit np.sum(data)

158 ms ± 8.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.97 ms ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
np.min(L)

0.006303983311221506

In [12]:
np.max(L)

0.9845548170017693

In [25]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.sum(X)

120

In [16]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [17]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [38]:
#得到所有元素的乘积
np.prod(X,axis=1)

array([    0,   840,  7920, 32760])

In [39]:
np.prod(X,axis=0)

array([   0,  585, 1680, 3465])

In [40]:
np.prod(X)

0

In [44]:
#值溢出
np.prod(X+1)

2004189184

In [85]:
a = 1
for i in range(1,13):
    a =a*i
print(a)

479001600


In [86]:
np.prod([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [1, 1, 1, 1]])

479001600

In [87]:
np.mean(X)

7.5

In [89]:
np.median(X)

7.5

In [90]:
np.percentile([1,2,3,4,5],q=25)

2.0

In [92]:
np.percentile([1,2,3,4,5],q=50)

3.0

In [93]:
np.percentile([1,2,3,4,5],q=75)

4.0

In [91]:
np.percentile?

In [94]:
np.var([1,2,3,4,5])

2.0

In [95]:
np.std([1,2,3,4,5])

1.4142135623730951